/*
 * Copyright (c) 2022.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package exposed.hydrogen.resources;

import team.unnamed.creative.ResourcePack;
import team.unnamed.creative.base.Writable;
import team.unnamed.creative.file.FileResource;
import team.unnamed.creative.metadata.Metadata;
import team.unnamed.creative.metadata.MetadataPart;
import team.unnamed.creative.metadata.PackMeta;

import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import java.nio.file.Files;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.List;

import static java.util.Optional.ofNullable;

public class Util {

    public static String getPublicIP() {
        // https://stackoverflow.com/questions/2939218/getting-the-external-ip-address-in-java
        try {
            URL whatismyip = new URL("https://checkip.amazonaws.com");
            BufferedReader in = new BufferedReader(new InputStreamReader(
                    whatismyip.openStream()));
            return in.readLine();
        } catch (IOException e) {
            e.printStackTrace();
            return "";
        }
    }
    /**
     * This code is completely generated by github copilot. I have no idea how it works. It just does.
     * @param file file to get hash from
     * @return hash of the file in string form
     * @throws IOException if file is not found
     * @throws NoSuchAlgorithmException if algorithm is not found (should never happen)
     */
    public static String getSHA1Hash(File file) throws IOException, NoSuchAlgorithmException {
        MessageDigest md = MessageDigest.getInstance("SHA-1");
        md.update(Files.readAllBytes(file.toPath()));
        return bytesToHex(md.digest());
    }
    /**
     * This code is completely generated by github copilot. I have no idea how it works. It just does.
     * @param file file to get hash from
     * @return hash of the file in byte array form
     * @throws IOException if file is not found
     * @throws NoSuchAlgorithmException if algorithm is not found (should never happen)
     */
    public static byte[] getSHA1HashBytes(File file) throws IOException, NoSuchAlgorithmException {
        MessageDigest md = MessageDigest.getInstance("SHA-1");
        md.update(Files.readAllBytes(file.toPath()));
        return md.digest();
    }
    /**
     * This code is completely generated by github copilot. I have no idea how it works. It just does.
     * @param bytes bytes to get hash from
     * @return hash of the file in byte array form
     * @throws NoSuchAlgorithmException if algorithm is not found (should never happen)
     */
    public static byte[] getSHA1HashBytes(byte[] bytes) throws NoSuchAlgorithmException {
        MessageDigest md = MessageDigest.getInstance("SHA-1");
        md.update(bytes);
        return md.digest();
    }

    public static String bytesToHex(byte[] bytes) {
        StringBuilder result = new StringBuilder();
        for (byte b : bytes) {
            result.append(Integer.toString((b & 0xff) + 0x100, 16).substring(1));
        }
        return result.toString();
    }
    /*public static void mergeZips(File zip1, File zip2) throws IOException {
        new ZipFile(zip1).mergeSplitFiles(ResourcePackHandler.MERGED_PACK_DIR.toFile());
        new ZipFile(zip2).mergeSplitFiles(ResourcePackHandler.MERGED_PACK_DIR.toFile());
    }*/

    public static ResourcePack compileResourcePack(List<FileResource> resources,
                                                   List<MetadataPart> metadataParts,
                                                   List<CustomResource> customResources,
                                                   String credits) {
        return ResourcePack.build(tree -> {
            tree.write(Metadata.builder()
                    .add(PackMeta.of(9,
                            ofNullable(Resources.getConfig().getString("description"))
                            .orElse("")))
                    .build());
            tree.write("credits.txt", Writable.bytes(("""
                       Generated by Resources using Creative by Unnamed Team
                       
                       Credits:
                       Creative - Unnamed Team
                       Resources - Hydrogen
                       
                       """ + credits).getBytes()));
            customResources.forEach(customResource -> tree.write(customResource.path(), customResource.data()));
            Metadata.Builder builder = Metadata.builder();
            metadataParts.forEach(part -> builder.add(MetadataPart.class, part));
            resources.forEach(tree::write);
        });
    }

    public static ResourcePack getPackFromFile(File file) throws IOException {
        byte[] bytes = Files.readAllBytes(file.toPath());
        return new ResourcePack(bytes,bytesToHex(bytes));
    }

}
